#!/bin/bash

read PCD_NAME < POOLCONTROLLER_DASHPANEL_NAME
read PCD_VERSION < POOLCONTROLLER_DASHPANEL_VERSION

echo pushing ${PCD_NAME}:${PCD_VERSION}

docker push ${PCD_NAME}:${PCD_VERSION}
docker push ${PCD_NAME}:latest

